### ISSUE TITLE
Expected member name or ';' after declaration specifiers, Eigen / EmguCV ?

### ISSUE THREAD

**Issue by MrMallIronmaker** [emgucv/emgucv#43]
Building EmguCV from source on OSX, I get this error, which I couldn't find in other build processes or bug lists.

```
In file included from /usr/local/include/eigen3/Eigen/src/Core/ArrayBase.h:93:
/usr/local/include/eigen3/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:184:1: error: 
      expected member name or ';' after declaration specifiers
sign() const
^
/Users/mariannedang/emgucv/opencv_contrib/modules/tracking/include/opencv2/tracking/onlineMIL.hpp:57:23: note: 
      expanded from macro 'sign'
#define  sign(s)  ((s > 0 ) ? 1 : ((s<0) ? -1 : 0))

...

In file included from /usr/local/include/eigen3/Eigen/src/Core/ArrayBase.h:93:
/usr/local/include/eigen3/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:184:1: error: 
      expected ')'
/Users/mariannedang/emgucv/opencv_contrib/modules/tracking/include/opencv2/tracking/onlineMIL.hpp:57:23: note: 
      expanded from macro 'sign'
#define  sign(s)  ((s > 0 ) ? 1 : ((s<0) ? -1 : 0))
                      ^
/usr/local/include/eigen3/Eigen/src/Core/../plugins/ArrayCwiseUnaryOps.h:184:1: note: 
      to match this '('
/Users/mariannedang/emgucv/opencv_contrib/modules/tracking/include/opencv2/tracking/onlineMIL.hpp:57:20: note: 
      expanded from macro 'sign'
#define  sign(s)  ((s > 0 ) ? 1 : ((s<0) ? -1 : 0))
                   ^
```

I'm running OSX 10.12.5, and just checked out the emgucv EMGUCV_3_1 branch. It's possible it's a versioning issue with Eigen, but I don't know how to check that, and other issues haven't been reported online yet.

Any help would be appreciated!

**Comment by emgucv** [comment]
I would recommend building with the "3.2.0" tag instead of the EMGUCV_3_1 branch.

But if you need to build with the 3.1 branch, and eigen is causing problems, you can disable Eigen by:

1. typing "ccmake ." in the emgu cv root source folder
2. finding the "WITH_EIGEN" entry
3. deselect it and re-run the configure. 
4. type "make" to build again

"Eigen" is not an essential component for Open CV and you can safely build the project without eigen support.

**Comment by emgucv** [comment]
Closing the ticket now. 

If you still have issues using the above recommendations, please re-open the ticket with error messages.

Thanks.
