### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ybchoo** [emgucv/emgucv#138]
Hi There 
I have tried your Emgu build using OpenCV 3.1.

I followed your instructor to copy plugins into Emgucv 
I get the following errors.
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Project\Unity\git\emgucv\CMakeFiles\CMakeTmp\Debug\cmTC_9396c.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Project/Unity/git/emgucv/CMakeFiles/CMakeTmp/Debug/cmTC_9396c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Project/Unity/git/emgucv/CMakeFiles/CMakeTmp/Debug/cmTC_9396c.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_9396c.dir\Debug\CheckFunctionExists.obj

CheckFunctionExists.obj : error LNK2019: unresolved external symbol _fseeko referenced in function _main [C:\Project\Unity\git\emgucv\CMakeFiles\CMakeTmp\cmTC_9396c.vcxproj]

C:\Project\Unity\git\emgucv\CMakeFiles\CMakeTmp\Debug\cmTC_9396c.exe : fatal error LNK1120: 1 unresolved externals [C:\Project\Unity\git\emgucv\CMakeFiles\CMakeTmp\cmTC_9396c.vcxproj]

Done Building Project "C:\Project\Unity\git\emgucv\CMakeFiles\CMakeTmp\cmTC_9396c.vcxproj" (default targets) -- FAILED.

When I follows your instruction on Unity I get the attached errors.
![unity3d build error](https://user-images.githubusercontent.com/3133110/41333397-3c5a45ca-6f14-11e8-97b5-5d8d31e68ebe.png)

**Comment by emgucv** [comment]
Are you using one of the Emgu CV for Unity commercial release? If so, do you get it from Unity Asset store or the Emgu CV website?

Using the commercial release, with a simple package import, all the setting and congfiguration will be handled for you. There is no need to build the package from source code.

Best regards,
Emgu support.

**Comment by emgucv** [comment]
Closing ticket now.
