### ISSUE TITLE
[BUG] Emgu.CV.runtime.maui.mini package  is not working in  .Net MAUI (.Net6.0/.Net7.0 maccatalyst 16.2) in Mac OS

### ISSUE THREAD

**Issue by hirendh** [emgucv/emgucv#850]
**Describe the bug**
Emgu.CV.runtime.maui.mini package  is not working .Net MAUI (.Net6.0/.Net7.0 maccatalyst 16.2) in Mac OS

** OS / Platform **
Mac OS

** .Net version **
 .net6  and .net7.0

**CPU Architecture**
ARM64

** Emgu CV package used**
Emgu.CV.runtime.maui.mini 

**To Reproduce**

**Set up in clean .Net MAUI project with  .net7.0-maccatalyst 16.2   and Run the app. App crashes and throws error:**

```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.2054/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: warning: ignoring file /Users/hirendhamecha/.nuget/packages/emgu.cv.runtime.maui.mini.macos/4.7.0.5276/lib/net6.0-maccatalyst13.2/Emgu.CV.Platform.Maui.Mac.resources/libcvextern_catalyst_arm64.a, building for Mac Catalyst-x86_64 but attempting to link with file built for Mac Catalyst-arm64
ld: warning: dylib (obj/Debug/net7.0-maccatalyst/maccatalyst-x64/nativelibraries/Contents/MonoBundle/libSystem.IO.Compression.Native.dylib) was built for newer Mac Catalyst version (13.5) than being linked (13.1)
ld: warning: dylib (obj/Debug/net7.0-maccatalyst/maccatalyst-x64/nativelibraries/Contents/MonoBundle/libSystem.Native.dylib) was built for newer Mac Catalyst version (13.5) than being linked (13.1)
ld: warning: dylib (obj/Debug/net7.0-maccatalyst/maccatalyst-x64/nativelibraries/Contents/MonoBundle/libSystem.Net.Security.Native.dylib) was built for newer Mac Catalyst version (13.5) than being linked (13.1)
ld: warning: dylib (obj/Debug/net7.0-maccatalyst/maccatalyst-x64/nativelibraries/Contents/MonoBundle/libSys 

```
**And also we tired with  .net6.0-maccatalyst 16.2 with same package and run the app and app crashes with following error:**

```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.46/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: warning: ignoring file /Users/hirendhamecha/.nuget/packages/emgu.cv.runtime.maui.mini.macos/4.7.0.5276/lib/net6.0-maccatalyst13.2/Emgu.CV.Platform.Maui.Mac.resources/libcvextern_catalyst_arm64.a, building for Mac Catalyst-x86_64 but attempting to link with file built for Mac Catalyst-arm64
Undefined symbols for architecture x86_64:
  "_VectorOfERStatGetMemorySize", referenced from:
     -u command line option
  "_VectorOfGMatGetMemorySize", referenced from:
     -u command line option
  "_VectorOfKeyLineGetMemorySize", referenced from:
     -u command line option
  "_VectorOfLinemodMatchGetMemorySize", referenced from:
     -u command line option
  "_VectorOfPose3DGetMemorySize", referenced from:
     -u command line option
  "_VectorOfTesseractResultGetMemorySize", referenced from:
     -u command line option
  "_VectorOfVectorOfERStatGetMemorySize", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to (Project12)

```

**Expected behavior**
Obviously no crash and no error of failing to load the library.

**Screenshots**

**Additional context**

**Comment by Strypper** [comment]
Hi any update on this ?

**Comment by emgucv** [comment]
Closing: as noted above, this was the same problem as #840 (the Mac Catalyst package shipped an arm64-only static library, breaking x86_64 links) and was fixed in 512916a950a0572bc1818bd3cb40f3ca9f34f24c, which shipped in the 4.8.0 release and every release since. If you still see a Catalyst link failure on a current package (4.13+ / 5.x), please open a new issue with the build log.
