### ISSUE TITLE
Emgucv doesn't build with Mono 5.0.1.1

### ISSUE THREAD

**Issue by zhen08** [emgucv/emgucv#31]
Microsoft (R) Visual C# Compiler version 2.0.0.61404
Copyright (C) Microsoft Corporation. All rights reserved.

/media/ubuntu/b8494351-d45f-45e7-9e1b-1e953eb450d9/emgucv/Emgu.CV.Cuda/Legacy/CudaBackgroundSubtractorFGD.cs(76,57): warning CS1573: Parameter 'forgroundMask' has no matching param tag in the XML comment for 'CudaBackgroundSubtractorFGD.Apply(IInputArray, IOutputArray, double)' (but other parameters do)
/media/ubuntu/b8494351-d45f-45e7-9e1b-1e953eb450d9/emgucv/Emgu.CV.Cuda/Legacy/CudaBackgroundSubtractorGMG.cs(34,57): warning CS1573: Parameter 'forgroundMask' has no matching param tag in the XML comment for 'CudaBackgroundSubtractorGMG.Apply(IInputArray, IOutputArray, double, Stream)' (but other parameters do)
error CS7027: Error signing output with public key from file '/media/ubuntu/b8494351-d45f-45e7-9e1b-1e953eb450d9/emgucv/Emgu.CV.World/../Emgu.CV.snk' -- mscoree.dll
Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/build.make:57: recipe for target 'Emgu.CV.World' failed
make[2]: *** [Emgu.CV.World] Error 1
CMakeFiles/Makefile2:9607: recipe for target 'Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all' failed
make[1]: *** [Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by emgucv** [comment]
Seems to be a Mono 5 compiler bug with no work around. 

Downgrade to the 4.2.1 mono mcs compiler supported by Ubutnu 16.04 repository and it will be able to compile.

**Comment by jeremejevs** [comment]
Since I'm building EmguCV for myself, I chose to just disable signing:

```diff
diff --git a/cmake/modules/CSharpMacros.cmake b/cmake/modules/CSharpMacros.cmake
index 9975086..36edc5b 100644
--- a/cmake/modules/CSharpMacros.cmake
+++ b/cmake/modules/CSharpMacros.cmake
@@ -381,7 +381,7 @@ MACRO(ADD_CS_RESOURCES resx resources)
 ENDMACRO(ADD_CS_RESOURCES)
 
 MACRO(SIGN_ASSEMBLY key) 
-  LIST(APPEND CS_FLAGS -keyfile:\"${key}\")
+  # LIST(APPEND CS_FLAGS -keyfile:\"${key}\")
 ENDMACRO(SIGN_ASSEMBLY)
 
 MACRO(GENERATE_DOCUMENT file)
```

**Comment by scemino** [comment]
I checked out version 3.2.0, I did what @jeremejevs suggested, and I followed the instructions from http://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Source but I when I run the project Emgu.CV.Example.Mac I still have this exception 

> System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.DllNotFoundException: libcvextern.dylib
  at at (wrapper managed-to-native) Emgu.CV.CvInvoke:RedirectError (Emgu.CV.CvInvoke/CvErrorCallback,intptr,intptr)
  at Emgu.CV.CvInvoke..cctor () [0x0009c] in Projects/scemino/emgucv/Emgu.CV/PInvoke/CvInvoke.cs:421
  --- End of inner exception stack trace ---
  at Emgu.CV.MatInvoke..cctor () [0x00001] in 
Projects/scemino/emgucv/Emgu.CV/Mat.cs:1154
  --- End of inner exception stack trace ---
  at Emgu.CV.Mat..ctor () [0x00000] in Projects/scemino/emgucv/Emgu.CV/Mat.cs:168
  at Emgu.CV.Mat..ctor (System.Int32 rows, System.Int32 cols, Emgu.CV.CvEnum.DepthType type, System.Int32 channels) [0x00000] in Projects/scemino/emgucv/Emgu.CV/Mat.cs:180
  at Emgu.CV.Example.Mac.ViewController.RunHelloWorld () [0x00001] in Projects/scemino/emgucv/Emgu.CV.Example/Mac/ViewController.cs:38
  at Emgu.CV.Example.Mac.ViewController.helloWorldClicked (Foundation.NSObject sender) [0x00001] in Projects/scemino/emgucv/Emgu.CV.Example/Mac/ViewController.cs:182
  at at (wrapper managed-to-native) AppKit.NSApplication:NSApplicationMain (int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00041] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/AppKit/NSApplication.cs:99
  at Emgu.CV.Example.Mac.MainClass.Main (System.String[] args) [0x00007] in Projects/scemino/emgucv/Emgu.CV.Example/Mac/Main.cs:15

What did I miss ?

**Comment by emgucv** [comment]
Should be fixed in cffc1f3b76c07e059b8b63f15e57c180897571ec. 

There is a bug in the latest version of Mono's implementation of code signing. To work around this issue, I use a modified version of jeremejevs' recommendation above. I added an option to globally disable code signing and I set code signing to false for all platforms except windows. 

Please give it a try.

**Comment by emgucv** [comment]
Fixed and is closing ticket now.

**Comment by frank-ozgul** [comment]
When building the latest EmguCv on Raspbian (Raspi3) I have the following error:
BTW, I am using the latest Mono version.
When I look in the logs prior to the last failure  lines of output, I see some "HDF5: Performing  Other test or Performing CXX Test" failures. as well
Any idea why I might be having this build problem?

[ 99%] Building ../../../libs/Emgu.CV.World.dll
Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
Copyright (C) Microsoft Corporation. All rights reserved.

/home/pi/emgucv/Emgu.CV/PInvoke/CvInvokeCore.cs(542,43): error CS0246: The type or namespace name 'IInputArray' could not be found (are you missing a using directive or an assembly reference?)
Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/build.make:496: recipe for target '../../../libs/Emgu.CV.World.dll' failed
make[2]: *** [../../../libs/Emgu.CV.World.dll] Error 1
CMakeFiles/Makefile2:10399: recipe for target 'Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all' failed
make[1]: *** [Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by miki87278** [comment]
Im building on latest Raspbian Buster on RPi 3B and I am getting same error 1 and error 2. Tried to correct .cs files but ended up like in screenshot
![screenshot](https://user-images.githubusercontent.com/32399848/65705368-987cca80-e088-11e9-95d1-87764ce66e88.png)
(followed emgucv Raspbian installation tutorial)
