### ISSUE TITLE
Emgucv doesn't build with Mono 5.4.0 on osx sierra

### ISSUE THREAD

**Issue by AbubakarSaad** [emgucv/emgucv#67]
Does anyone have idea how to build emgucv? I been stuck on this issue for three days now, I tried everything I could find on google. 

/Users/abubakarsaad/Unity/emgucv/Emgu.CV.Cuda/Legacy/CudaBackgroundSubtractorFGD.cs(76,57): warning CS1573: Parameter 'forgroundMask' has no matching param tag in the XML comment for 'CudaBackgroundSubtractorFGD.Apply(IInputArray, IOutputArray, double)' (but other parameters do)
/Users/abubakarsaad/Unity/emgucv/Emgu.CV.Cuda/Legacy/CudaBackgroundSubtractorGMG.cs(34,57): warning CS1573: Parameter 'forgroundMask' has no matching param tag in the XML comment for 'CudaBackgroundSubtractorGMG.Apply(IInputArray, IOutputArray, double, Stream)' (but other parameters do)
error CS7027: Error signing output with public key from file '/Users/abubakarsaad/Unity/emgucv/Emgu.CV.World/../Emgu.CV.snk' -- mscoree.dll
make[2]: *** [Emgu.CV.World] Error 1
make[1]: *** [Emgu.CV.World/CMakeFiles/Emgu.CV.World.dir/all] Error 2
make: *** [all] Error 2

Any help is greatly appreciated. 

Thank you

**Comment by heavyBug** [comment]
@AbubakarSaad found any luck in building the emguCV for mac???

**Comment by emgucv** [comment]
If you are using the 3.2 tag you may have the signing problem because a bug introduced in the Mono compiler when code signing is called directly from command line.

The latest development code should call msbuild  to sign the dll and do not have the signing issue.

The last time I build with 88c10f6b7bf605a72851f7d6633398193332b2b1 using the "configure_x86_64" script under platform/osx compiles on OSX sierra without any signing issues.

**Comment by emgucv** [comment]
Closing ticket now.
