### ISSUE TITLE
Building OpenCv 4.7/5.0 fails on a Windows machine with Cuda 12 [needs updates from the official OpenCv repo]

### ISSUE THREAD

**Issue by netcorefan1** [emgucv/emgucv#822]
Hello,
I'm opening this topic because I've been unable to find any info elsewhere. My configuration is Windows 11 x64 + VS2022 and I only need it to run on such platform.

- I have the whole Cuda 12 SDK (along with all the other related stuff) and I suppose I need to build from Git in order to get the latest features of my card and the desired features of OpenCv. My card has a compute capability of 8.6, therefore I used `Build_Binary_x86-64_cuda-dev-sm86.bat`.
During Vtk configuration I got a `Looking for a Fortran compiler - NOTFOUND`. I suppose that this is main reason for ending up with a `VTK support:  NO` and `SSE SSE2 SSE3` as the only features recognized in `CPU/HW features`.
There are other features that I would like to include (GStreamer, Vtk-m etc) and I have all the binaries compiled with vcpkg. However, I can't link the vcpkg toolchain because the CMAKE_TOOLCHAIN_FILE option is set to emgu generated toolchain. How can I do?

- I saw [EMGUCV_5_0](https://github.com/emgucv/emgucv/tree/EMGUCV_5_0) branch and I was wondering if I was better off to directly start working with OpenCv 5 rather than working on an old version that will be replaced soon. What is the current status? Last commit is around 3 months ago and I was wondering what it is expected to not work with a fresh build done from the official [branch](https://github.com/opencv/opencv/tree/5.x).

- Could [NumSharp](https://github.com/SciSharp/NumSharp) and/or [Numpy.NET](https://github.com/SciSharp/Numpy.NET) work out of the box or with some adaptations? The more difficult task when translating Python code into C# is the Numpy section and those libraries can make the process easy.

- I have an AMD Ryzen 7 processor and the recommended numerical libraries are [AMD Optimizing CPU Libraries (AOCL)](https://www.amd.com/en/developer/aocl.html). What should be done to integrate such libraries? I can only see stuff related to Intel, but nothing for AMD.
 
Thanks

**Comment by obabac** [comment]
I was also wondering about the status of [EMGUCV_5_0](https://github.com/emgucv/emgucv/tree/EMGUCV_5_0)

**Comment by emgucv** [comment]
We are working on the 4.7 release. Emgu CV 5.0 is tracking Open CV 5.0, it won't be ready until Open CV 5.0 is out. The v5.0 branch build with no issues on our side.

**Comment by netcorefan1** [comment]
> I was also wondering about the status of [EMGUCV_5_0](https://github.com/emgucv/emgucv/tree/EMGUCV_5_0)
I didn't tried to build 5.0 because I'm already having so many troubles with 4.7. Did you managed to get it working?

Cmake expect to find the Netwide Fortran compiler in `AppData\Local\bin\NASM`.
I have to figure out how to manually set the location of the YASM compiler, but, as a quick fix, I just used the official Netwide installer and the problem has gone away. 
I also got a `Could NOT find Perl (missing: PERL_EXECUTABLE)` which I fixed by installing StrawberryPerl. Hope to find a way to directly link to a portable perl rather than relying to a full system install.

Other errors...

### Unable to find a Fortran compiler (even after having installed the [Intel Fortran Compiler](https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#fortran))
```
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - NOTFOUND
```
### Unrecognized CPU capabilities:
```
> From Emgucv:
--  CPU/HW features:
--  Baseline:                    SSE SSE2 SSE3
--  requested:                 SSE3

> Expected:
CPU/HW features:
--  Baseline:                    SSE SSE2 SSE3
--  requested:                 SSE3
--  Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--  requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--  SSE4_1 (18 files):         + SSSE3 SSE4_1
--  SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--  FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--  AVX (8 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--  AVX2 (36 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--  AVX512_SKX (8 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
```
### Unrecognized harfbuzz version:
```
-- Looking for vidcap.h
-- Looking for vidcap.h - found
-- Looking for d3d11_4.h
-- Looking for d3d11_4.h - found
-- freetype2:   YES (ver 2.10.4)
-- harfbuzz:    YES (ver )
-- Julia not found. Not compiling Julia Bindings.
```
### Tesseract not found (not sure if this is related to this [bug](https://github.com/emgucv/emgucv/issues/797)):
```
-- Could NOT find TESSERACT (missing: TESSERACT_LIBRARY TESSERACT_INCLUDE_DIRS)
-- Tesseract:   NO
-- Processing WORLD modules...
```
### VTK not found:
```
-- Could NOT find VTK (missing: VTK_DIR)
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- ADE: Downloading v0.1.2a.zip from https://github.com/opencv/ade/archive/v0.1.2a.zip
--   GUI:
--     Win32 UI:                    YES
--     VTK support:                 NO
```

### hdf5 tests failures:
```
  H5.c
  H5checksum.c
  H5dbg.c
  H5mpi.c
  H5system.c
..\hdf5\src\H5system.c(1085,47): warning C4090: '=': different 'const' qualifiers [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5system.c(1135,47): warning C4090: '=': different 'const' qualifiers [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
  H5timer.c
..\hdf5\src\H5timer.c(117,19): error C2079: 'rusage' uses undefined struct 'rusage' [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(126,5): warning C4013: 'getrusage' undefined; assuming extern returning int [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(126,5): error C2065: 'RUSAGE_SELF': undeclared identifier [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(127,35): error C2224: left of '.ru_utime' must have struct/union type [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(128,36): error C2224: left of '.ru_utime' must have struct/union type [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(129,35): error C2224: left of '.ru_stime' must have struct/union type [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
..\hdf5\src\H5timer.c(130,36): error C2224: left of '.ru_stime' must have struct/union type [..\hdf5\build_x86_64\src\hdf5-static.vcxproj]
  H5trace.c
```
### "Error in configuration process, project files may be invalid" in CMake GUI:
```
Using toolchain file: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake
CMake Error at build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake:48 (message):
  Internal error
Call Stack (most recent call first):
  ../cmake-3.26.0-rc5-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project)
Configuring incomplete, errors occurred!
```
It occurs even when the configuration completes (Configuring done > Generating done > Build files have been written to: ../emgucv/build_x86_64).

The generated VS solution fails to compile with 503 errors, 1819 warnings and 1795 messages:
```
 fatal  error C1189: #error:  This file was generated by an older version of protoc which is (compiling source file ..\emgucv\opencv\modules\dnn\misc\caffe\opencv-caffe.pb.cc)
fatal  error C1189: #error:  This file was generated by an older version of protoc which is (compiling source file ..\emgucv\opencv\modules\dnn\misc\tensorflow\tensor.pb.cc
Error C2065	'arena': undeclared identifier	libprotobuf	..\emgucv\opencv\3rdparty\protobuf\src\google\protobuf\arenastring.cc
Error E0289	no instance of constructor "google::protobuf::internal::ArenaStringPtr::ArenaStringPtr" matches the argument list	opencv_dnn	..emgucv\opencv\modules\dnn\misc\tensorflow\attr_value.pb.cc
========== Build: 115 succeeded, 26 failed, 0 up-to-date, 11 skipped ==========
```
Around 20 errors are generated from mixed projects (file not found or LINK1181: cannot open \release\xxxx.lib)
All the other errors only from openvc_dnn and libprotobuf.

I have no idea on what should I do, I can't even use CMake configurator and try to see if I can fix something there. I'm wondering if there is a way to use the vcpkg toolchain rather then the generated `depthai-core/generated/toolchain.cmake`.  I have all the required packages and all of them compiled without none of such problems.

Also...is there some cleaner script? I have to delete the entire folder and use a copy on each attempt. I would also appreciate if someone can link some useful source on the building process. The official [Building from Git](https://emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git) just refers to the main steps and the linked [discussion forum](https://emgu.com/forum) does not exists.

**Comment by netcorefan1** [comment]
> We are working on the 4.7 release. Emgu CV 5.0 is tracking Open CV 5.0, it won't be ready until Open CV 5.0 is out. The v5.0 branch build with no issues on our side.

Ops...your comment popped out while I was writing my previous comment and I missed it. If you say that CV 5 compiles, I'm tempted to try it out, but are at least the main features usable? If 4.7 is so problematic, may be is better to directly switch to 5.0 and keep hard by working in limited mode until Open CV 5.0 is out?

My previous comment contains all the details about my attempts with 4.7 (failures can be my fault!). If there is something I can do to help, just let me know!

**Comment by netcorefan1** [comment]
> We are working on the 4.7 release. Emgu CV 5.0 is tracking Open CV 5.0, it won't be ready until Open CV 5.0 is out. The v5.0 branch build with no issues on our side.

@emgucv Unfortunately v5.0 branch (as is) does not compile on Windows with Cuda 12.
The troubles I encountered are pretty much the same of 4.7, but I have been able to find the cause of most issues.

- Many people use vcpkg VS integration which causes some project to fail (even without VS opened). This feature cause MSBuild to automatically pick up the vcpkg version of the headers instead of the local ones. I have been able to partially fix this by creating a `Directory.Build.props`:
```
<Project>
    <PropertyGroup>
        <VcpkgEnabled>false</VcpkgEnabled>
    </PropertyGroup>
</Project>
```
It works until the file gets replaced by emgucv and building starts failing again. I believe that this could be fixed if you create this file from the beginning and ensure that VcpkgEnabled property does not get removed during the process.

- As a quick fix, the previous problem can be bypassed by completely uninstalling VS integration through `vcpkg integrate remove`. The process will then continue until the following error:
`modules/core/include/opencv2/core/cuda/common.hpp(99): error: identifier "textureReference" is undefined`
This occurs because CUDA 12.0 [dropped support](https://forums.developer.nvidia.com/t/cuda-12-0-still-support-for-texture-reference-support-for-pascal-architecture-warp-synchronous-programming/237284/1) for legacy texture references.
This, along with other Cuda related problems, have been fixed many time ago (see [here](https://github.com/opencv/opencv/commits?author=cudawarped) and [here](https://github.com/opencv/opencv_contrib/commits?author=cudawarped)).
While looking at [cudev](https://github.com/emgucv/opencv_contrib/tree/emgucv_5.x/modules/cudev) section I saw that last update is around 2 years ago. The same for other sections in this and other branches.
May I ask why there is such long distance?
I've been able to apply Cuda patches except abd3ca8bf8c452a5b4c3a883655de28120f8ca06. Compilation continued for a good a mount of time until the following:
```
1>Target CustomBuild:
1>  Checking Build System
1>  CMake is re-running because ../emgucv/build_x86_64/CMakeFiles/generate.stamp is out-of-date.
1>    the file '../emgucv/build_x86_64/CMakeFiles/3.25.1-msvc1/CMakeCCompiler.cmake'
1>    is newer than '../emgucv/build_x86_64/CMakeFiles/generate.stamp.depend'
1>    result='0'
1>  -- Using specified toolchain file: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake combined into: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake
1>  CMake Error at build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake:48 (message):
1>    Internal error
1>  Call Stack (most recent call first):
1>    build_x86_64/CMakeFiles/3.25.1-msvc1/CMakeSystem.cmake:6 (include)
1>    Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project)
1>
1>
1>  -- Configuring incomplete, errors occurred!
1>  See also "../emgucv/build_x86_64/CMakeFiles/CMakeOutput.log".
1>  See also "../emgucv/build_x86_64/CMakeFiles/CMakeError.log".
1>  CMake Configure step failed.  Build files cannot be regenerated correctly.  Attempting to stop IDE build.
1>  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for '..\emgucv\build_x86_64\CMakeFiles\f5307fd9f4e2801cbab505d205093c0f\generate.stamp.rule' exited with code 1.
1>Done building target "CustomBuild" in project "ZERO_CHECK.vcxproj" -- FAILED.
1>
1>Done building project "ZERO_CHECK.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for '..\emgucv\build_x86_64\CMakeFiles\f5307fd9f4e2801cbab505d205093c0f\generate.stamp.rule' exited with code 1.
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.39
2>------ Build started: Project: opencv_world, Configuration: Release x64 ------
2>Build started 16/03/2023 12:45:27.
2>Target ResolveProjectReferences:
2>  Target _PrepareForReferenceResolution:
2>    Target _PrepareForReferenceResolution:
2>  Target GetNativeManifest:
2>    Target GetNativeManifest:
2>      Target GetNativeManifest:
2>    Target GetNativeManifest:
2>      Target GetNativeManifest:
2>          Target GetNativeManifest:
2>Target InitializeBuildStatus:
2>  Touching "opencv_world.dir\Release\opencv_world.tlog\unsuccessfulbuild".
2>Target CustomBuild:
2>  Building Custom Rule ../emgucv/opencv/modules/world/CMakeLists.txt
2>  CMake is re-running because ../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/generate.stamp is out-of-date.
2>    the file '../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/cuda_compile_1.dir/__/__/__/opencv_contrib/modules/cudaarithm/src/cuda/cuda_compile_1_generated_absdiff_mat.cu.obj.depend'
2>    is newer than '../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/generate.stamp.depend'
2>    result='-1'
2>  -- Using specified toolchain file: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake combined into: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake
2>  CMake Error at build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake:48 (message):
2>    Internal error
2>  Call Stack (most recent call first):
2>    build_x86_64/CMakeFiles/3.25.1-msvc1/CMakeSystem.cmake:6 (include)
2>    Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project)
2>
2>
2>  -- Configuring incomplete, errors occurred!
2>  See also "../emgucv/build_x86_64/CMakeFiles/CMakeOutput.log".
2>  See also "../emgucv/build_x86_64/CMakeFiles/CMakeError.log".
2>  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for '..\emgucv\opencv\modules\world\CMakeLists.txt' exited with code 1.
2>Done building target "CustomBuild" in project "opencv_world.vcxproj" -- FAILED.
2>
2>Done building project "opencv_world.vcxproj" -- FAILED.
2>
2>Build FAILED.
2>
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for '..\emgucv\opencv\modules\world\CMakeLists.txt' exited with code 1.
2>    0 Warning(s)
2>    1 Error(s)
2>
2>Time Elapsed 00:00:00.98
========== Build: 0 succeeded, 2 failed, 11 up-to-date, 0 skipped ==========
```
I'm not sure if this depends from my inability to apply abd3ca8bf8c452a5b4c3a883655de28120f8ca06:
```
Auto-merging modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu
CONFLICT (content): Merge conflict in modules/cudalegacy/src/cuda/NCVBroxOpticalFlow.cu
Auto-merging modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp
CONFLICT (content): Merge conflict in modules/cudev/include/opencv2/cudev/ptr2d/texture.hpp
```
Emgucv is so many commits behind the official repos and probably there are deeper changes that I can't fix by simply patching some Cuda files.

**Comment by emgucv** [comment]
Emgu CV 4.7 is building with CUDA 12. 

Emgu CV 5.x's opencv & opencv_contrib 5.x branch is last update at Dec 2022, and is only a few commits behind the official opencv & opencv_contrib 5.x branch. We just updated then to current (March 19, 2023).

We are docusing our resource with Emgu CV 4.7 release. We will look into 5.x after 4.7 release is completed.

**Comment by netcorefan1** [comment]
> Emgu CV 4.7 is building with CUDA 12.
> 
> Emgu CV 5.x's opencv & opencv_contrib 5.x branch is last update at Dec 2022, and is only a few commits behind the official opencv & opencv_contrib 5.x branch. We just updated then to current (March 19, 2023).
> 
> We are focusing our resource with Emgu CV 4.7 release. We will look into 5.x after 4.7 release is completed.

Thanks for your help. Do you mean `"4.7 + Cuda 12 + Windows + msvc 143"` ? Unfortunately does not work on my side. Below is what I get after 2 hours of compilation.

`Build_Binary_x86-64_cuda-dev-sm86.bat` (or even `Build_Binary_x86-64_cuda_doc.bat`):
```
Building Custom Rule ../emgucv/opencv/modules/world/CMakeLists.txt
CMake is re-running because ../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/generate.stamp is out-of-date.
the file '../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/cuda_compile_1.dir/__/__/__/opencv_contrib/modules/cudaarithm/src/cuda/cuda_compile_1_generated_absdiff_mat.cu.obj.depend' is newer than '../emgucv/build_x86_64/opencv/modules/world/CMakeFiles/generate.stamp.depend'
  result='-1'
  -- Using toolchain file: ../emgucv/build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake
  CMake Error at build_x86_64/Emgu.CV.Extern/depthai-core/generated/toolchain.cmake:48 (message):
  Internal error
Call Stack (most recent call first):
  build_x86_64/CMakeFiles/3.25.1-msvc1/CMakeSystem.cmake:6 (include)
  Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project)
CMake Error at Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project):
 No CMAKE_CXX_COMPILER could be found.
CMake Error at Emgu.CV.Extern/depthai-core/CMakeLists.txt:36 (project):
 No CMAKE_C_COMPILER could be found.
-- Configuring incomplete, errors occurred!
```
It looks like Cuda is a real challenge! The official [OpenCv](https://github.com/opencv/opencv) compiles fine under Cuda 12 along with all modules. There must be something wrong in CMake which cause to rerun configuration. I didn't changed any build options.

**Comment by netcorefan1** [comment]
I'm going to close the issue because after many days of trials I have finally been able to compile 4.7.
Regarding the invalid generated configuration showed in the pic above I simply solved by providing the required properties directly from the script.
Regarding the `CMake is re-running because` error, I believe that this is the cause:
`CUDA: MSVS generator is detected. Disabling CMake re-run checks (CMAKE_SUPPRESS_REGENERATION=ON). You need to run CMake manually if updates are required.`
Not sure if if this is the correct way to handle this, but once I enabled CMake re-run checks, the error has gone away and solution compiled.
