### ISSUE TITLE
new Image<Bgr, byte> 4.4

### ISSUE THREAD

**Issue by leichenstarre** [emgucv/emgucv#363]
How i can create an new Image?
new Image<Bgr, byte>("path to png"); works fine with 4.1, but not with 4.4.

**Comment by emgucv** [comment]
Works in v4.4 release.

Source code for the implementation can be found here:
https://github.com/emgucv/emgucv/blob/4.4.0/Emgu.CV/Core/Image.cs#L115

Do you have a compilation error or runtime error?

**Comment by leichenstarre** [comment]
Ty for your answer.
I found a solution
with 4.4 and net standard,  I also had to install
- emgu.cv.ui
- emgu.cv.runtime.window
- emgu.cv.bitmap

new Bitmap(openfiledialog.FileName).ToImage<Bgr, byte>();

**Comment by emgucv** [comment]
The Image<,> constructor that accepts a ".png" file name should also work.

**Comment by emgucv** [comment]
Closing ticket now.
